### ISSUE TITLE
Footer background not full-width

### ISSUE THREAD

**Issue by hartpableo** [Mikerniker/CodeConnect_P3#1]
![image](https://github.com/user-attachments/assets/568d5649-3203-4dbd-83ba-7daede0ac98d)

Footer background not full-width

**Comment by Mikerniker** [comment]
Hi @Hart, I fixed the [background-color](https://github.com/Mikerniker/CodeConnect_P3/commit/bd3de33698aa57d08923725ea7ae39729860344c). Let me know if this works for you.

**Comment by hartpableo** [comment]
Hi @Mikerniker looks better, one more thing is that the logo is not aligned with the rest of the content

![image](https://github.com/user-attachments/assets/28af8494-cd34-454d-b336-1c9768bca662)

Also might be worth reviewing your implementation of the container :smile: 

![image](https://github.com/user-attachments/assets/817ecfb8-8a29-4377-9dac-42ca0dc870a3)

**Comment by Mikerniker** [comment]
Hi @hartpableo , I tried aligning the [footer with the rest of the content](https://github.com/Mikerniker/CodeConnect_P3/commit/04bf856f0d663b6c2b655f56c07b4a86fa9534cb)
